import Head from 'next/head'

import CareersComponent from 'src/components/Careers'

import styles from 'src/styles/Home.module.css'

export default function Careers() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CareersComponent />
        </div>
    )
}
