import Head from "next/head"
import { Box } from "@chakra-ui/react"

import styles from 'styles/Home.module.css'

import HomeComponent from "src/components/Home"

export default function HomePage() {
  return (
    <Box className={styles.container} style={{ width: '100%' }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeComponent />
    </Box>
  )
}
