import Head from 'next/head'

import ServicesComponent from 'src/components/Services'

import styles from 'styles/Home.module.css'

export default function Services() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ServicesComponent />
        </div>
    )
}
